version: '3'
services:
  sim:
    image: f1tenth_gym_ros
    volumes: 
      - .:/sim_ws/src/f1tenth_gym_ros
      - ./empty_folder:/sim_ws/src/f1tenth_gym_ros/nodes # make nodes an empty folder
      - ./nodes:/sim_ws/src/
    environment:
      - DISPLAY=novnc:0.0
    networks:
      - x11
    stdin_open: true
    tty: true 
  novnc:  
    image: theasp/novnc:latest
    environment:
      - DISPLAY_WIDTH=1728
      - DISPLAY_HEIGHT=972
    ports:
      - "8081:8080"
    networks:
      - x11
networks:
  x11: